### ISSUE TITLE
Document count (distinct expr)

### ISSUE THREAD

**Issue by CharlieSYH** [risingwavelabs/risingwave-docs-legacy#220] opened 2022-08-12 05:08 UTC
### Related code PR

https://github.com/singularity-data/risingwave/pull/3920

### Which part(s) of the docs might be affected or should be updated? And how?

Looks like we didn't document this function before. Add a new function count (distinct expression) to https://www.risingwave.dev/docs/latest/sql-function-aggregate/.

This whole section (Aggregate functions) needs a revamp. Need to document descriptions and examples.

### Notes
Xiangjin: The support is buggy/incomplete yet. It may produce wrong result in streaming: https://github.com/singularity-data/risingwave/issues/3589 . 
Check if the bug is fixed in the following versions.

### Reference

Google count distinct sql

**Comment by hengm3467** [comment] 2022-09-01 05:29
@bernscode  I just confirmed with Xiangjin. The feature is now completely implemented, so we can update the docs for it now. Since you are expanding the Aggregate functions page now, I think it makes sense that you take this issue. :)

**Comment by CharlieSYH** [comment] 2022-09-01 07:19
> I just confirmed with Xiangjin. The feature is now completely implemented, so we can update the docs for it now. Since you are expanding the Aggregate functions page now, I think it makes sense that you take this issue. :)

 @hengm3467 In which version? Do we need to add it to the release notes?

**Comment by hengm3467** [comment] 2022-09-07 08:51
@bernscode I just assigned this one to myself, as I'm working on a new topic about value expressions, in which this one will be a section, or part of that section.

**Comment by bernscode** [comment] 2022-09-08 01:44
Okay, sounds good. Thanks for the heads up!

**Comment by hengm3467** [comment] 2022-10-08 07:26
fixed in https://github.com/risingwavelabs/risingwave-docs/pull/190
Changes can be found from https://www.risingwave.dev/docs/latest/sql-syntax-value-exp/ and https://www.risingwave.dev/docs/latest/sql-function-aggregate/

**Closed as completed by hengm3467** 2022-10-08 07:26 UTC
Labels: documentation
